apiVersion: batch/v1
kind: CronJob
metadata:
  name: azure-dns-updater
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: azure-dns-updater
            image: ghcr.io/qwerty-iot/azure-dns-updater/azure-dns-updater:latest
            env:
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: subscription_id
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: tenant_id
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: client_id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: client_secret
            - name: DNS_ZONE
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: dns_zone
            - name: DNS_RECORD
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: dns_record
            - name: DNS_RESOURCE_GROUP
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: dns_resource_group
          restartPolicy: Never
